version: '3'

services:
  icecast-analytics:
    image: bushrangers/docker-icecast-google-analytics
    container_name: icecast-analytics
    restart: always
    privileged:  true
    network_mode: host
    volumes:
        - ./config/config.xml:/config/config.xml
